project:
  type: website

website:
  title: "Maya Hirsch"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

execute:
  freeze: auto
  

